version: "3.2"
services:
  web:
    build: .
    image: 1234567890.dkr.ecr.us-east-1.amazonaws.com/my-service:0.1.0
    ports:
    - published: 80
      target: 8080
    environment:
      FOO: bar
    labels:
      aws.ecs.fargate.deploy: 1